kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: ci-cd
  name: runner
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  verbs:
  - get
  - create
  - delete
  - list
  - watch
  - update

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: runner
  namespace: ci-cd
subjects:
- kind: ServiceAccount
  name: default
  namespace: ci-cd
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: ClusterRole
  name: runner
  apiGroup: rbac.authorization.k8s.io
