apiVersion: apps/v1
kind: Deployment
metadata:
  name: runner
  namespace: ci-cd
  labels:
    app.kubernetes.io/name: runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: runner
  template:
    metadata:
      labels:
        app.kubernetes.io/name: runner
    spec:
      containers:
      - name: runner
        image: drone/drone-runner-kube:latest
        ports:
        - containerPort: 3000
        env:
        - name: DRONE_RPC_HOST
          value: "drone"
        - name: DRONE_RPC_PROTO
          value: "http"
        - name: DRONE_RPC_SECRET
          valueFrom: 
            secretKeyRef: 
              name: drone-rpc-secret
              key: drone-rpc-secret 